# --- Ports ---
UDP_DISCOVERY_PORT = 37020
UDP_VIDEO_PORT = 8486
CONTROL_TCP_PORT = 8600 

# --- Discovery Protocol ---
HANDSHAKE_EXPECTED = b"PC_CLIENT"
HANDSHAKE_REPLY_PREFIX = "PI_SERVER"

# --- Network settings ---
UDP_BUFFER_SIZE = 65536
TCP_RECV_CHUNK = 1024
DISCOVERY_RECV_CHUNK = 1024

# --- Timeouts, Timers and Rates ---
UDP_TIMEOUT = 1.0
UDP_VIDEO_TIMEOUT = 1.0
TCP_RECV_TIMEOUT = 0.5
TCP_CONNECT_TIMEOUT = 1.0
VIDEO_STREAM_TIMEOUT = 0.5
NETWORK_JOIN_TIMEOUT = 2.0
RECONNECT_DELAY = 0.5
HEARTBEAT_INTERVAL = 10 # In ms
GUI_REFRESH_RATE = 16 # In ms, ~60 FPS

# --- Video Decoding ---
VIDEO_HEADER_SIZE = 7
MAGIC_BYTE = 0xAA
FRAME_BUFFER_LIMIT = 100

# --- Logging ---
LOG_PREFIX = "[CLIENT]"
LOG_DIR = "logs"
LOG_MAX_BYTES = 2 * 1024 * 1024
LOG_BACKUP_COUNT = 4

# --- Telemetry Alert Thresholds ---
ALERT_CPU_TEMP = 75.0
ALERT_HULL_HUM = 65.0
ALERT_HULL_TEMP = 50.0

# --- Video display settings ---
WINDOW_NAME = "Hindenburg Drone Controller"

# --- Controller Settings ---
JOYSTICK_DEADZONE = 0.10
DEFAULT_POWER_SCALE = 0.20
POWER_STEP = 0.05
POWER_MIN = 0.05
POWER_MAX = 1.00
AXIS_YAW = 0
AXIS_FWD = 1
AXIS_DEPTH_ALT = 3
AXIS_DEPTH = 4